### ISSUE TITLE
What is it? It makes application crush

### ISSUE THREAD

**Issue by kunlongxu** [bryce-co/XcodeVimMap#2]
https://github.com/bryce-co/XcodeVimMap/blob/4570efc1f3ef6e4256b93ccd84cc4b8999a8dd39/XcodeVimMap.xcodeproj/xcshareddata/xcschemes/XcodeVimMap.xcscheme#L47

**Comment by brycebostwick** [comment]
I had my local scheme set up to launch Xcode-13.0b4 in debug mode while building this plugin; I should have removed this before pushing, sorry.

I remade the Xcode project a moment ago (mostly to make notarization easier) - this is gone as part of that commit 👍
